# Generated by Django 4.0.5 on 2022-06-18 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nysc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='state_code',
            field=models.CharField(max_length=11),
        ),
    ]
