# Generated by Django 4.0.5 on 2022-09-14 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nysc', '0002_alter_database_state_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('state_code', models.CharField(max_length=11)),
                ('ppa', models.CharField(max_length=100)),
                ('bank_name', models.CharField(max_length=50)),
                ('account_number', models.CharField(max_length=10)),
            ],
        ),
    ]
